#!/bin/sh
#TODO: Adapted to various cgroupfs mount
. /usr/lib/crund/crund_def

cgroup_init()
{
	echo 1 > ${CGROUP_DIR}/cgroup.clone_children
	echo 1 > ${CGROUP_DIR}/memory.use_hierarchy
	cgroup.clone_children
	PID=$1
	mkdir ${CGROUP_ROOT}
	echo ${PID} > ${CGROUP_ROOT}/cgroup.procs
	echo ${PID} > ${CGROUP_ROOT}/tasks
}

cgroup_exit()
{
	rmdir ${CGROUP_ROOT}
}

cgroup_container_setup()
{
	CONTAINER_ID=$1
	mkdir ${CGROUP_ROOT}/${CONTAINER_ID}
	echo "a *:* rwm" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.deny
	echo "c 1:5 rwm" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
	echo "c 1:3 rwm" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
	echo "c 1:9 rwm" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
	echo "c 1:8 rwm" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
	echo "c 5:0 rwm" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
	echo "c 5:1 rwm" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
	echo "c *:* m" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
	echo "b *:* m" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
	echo "c 1:7 rwm" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
	echo "c 136:* rwm" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
	echo "c 5:2 rwm" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
	echo "c 10:200 rwm" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
}

cgroup_container_start()
{
	CONTAINER_ID=$1
	PID=$2
	echo ${PID} > ${CGROUP_ROOT}/${CONTAINER_ID}/cgroup.procs
	echo ${PID} > ${CGROUP_ROOT}/${CONTAINER_ID}/tasks
}

cgroup_container_stop()
{
	CONTAINER_ID=$1
	rmdir ${CGROUP_ROOT}/${CONTAINER_ID}
}

cgroup_container_add_dev()
{
	DEVICES_LIST=''
	ARGS=$(getopt -o d: -n "$0" -- "$@")
	eval set -- "${ARGS}"
	while true
	do
		case "$1" in
			'-d')
				DEVICES_LIST="${DEVICES_LIST} $2"
				shift 2
				;;
			'--')
				shift
				break
				;;
		esac
	done
	DEVICES_LIST=${DEVICES_LIST:1}
	CONTAINER_ID=$1
	for line in ${DEVICES_LIST}
	do
		DEV_TYPE=$(echo $line | awk -F ',' '{print $NF}')
		MAJOR_NUM=$(echo $line | awk -F ',' '{print $2}')
		MINOR_NUM=$(echo $line | awk -F ',' '{print $3}')
		echo "${DEV_TYPE} ${MAJOR_NUM}:${MINOR_NUM} rwm" > ${CGROUP_ROOT}/${CONTAINER_ID}/devices.allow
	done
}
